# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run analyzer
      run: mvn --projects analyzer --also-make clean spring-boot:run
    - name: Run integration tests
      run: mvn --projects integration-tests --also-make package
    - name: Install results-ui dependencies
      run: cd results-ui && npm i
    - name: Build results-ui
      run: cd results-ui && npm run build
    - name: deploy results-ui to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: results-ui/dist/results-ui
